let student=[{
    "id": 1,
    "first_name": "Tiphanie",
    "last_name": "Keerl",
    "email": "tkeerl0@mail.ru",
    "gender": "Female"
  }, {
    "id": 2,
    "first_name": "Karlotta",
    "last_name": "Baleine",
    "email": "kbaleine1@creativecommons.org",
    "gender": "Polygender"
  }, {
    "id": 3,
    "first_name": "Rosalia",
    "last_name": "Chalice",
    "email": "rchalice2@com.com",
    "gender": "Female"
  }, {
    "id": 4,
    "first_name": "Sukey",
    "last_name": "Kilday",
    "email": "skilday3@seesaa.net",
    "gender": "Female"
  }, {
    "id": 5,
    "first_name": "Sandie",
    "last_name": "Burrells",
    "email": "sburrells4@goodreads.com",
    "gender": "Female"
  }, {
    "id": 6,
    "first_name": "Marge",
    "last_name": "Hallowell",
    "email": "mhallowell5@irs.gov",
    "gender": "Agender"
  }, {
    "id": 7,
    "first_name": "Tadeo",
    "last_name": "Holstein",
    "email": "tholstein6@wikia.com",
    "gender": "Male"
  }, {
    "id": 8,
    "first_name": "Libbie",
    "last_name": "Burge",
    "email": "lburge7@hostgator.com",
    "gender": "Female"
  }, {
    "id": 9,
    "first_name": "Consuela",
    "last_name": "Surby",
    "email": "csurby8@cargocollective.com",
    "gender": "Female"
  }, {
    "id": 10,
    "first_name": "Haley",
    "last_name": "Alliberton",
    "email": "halliberton9@state.gov",
    "gender": "Female"
  }]
module.exports= student 